### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by khw11044** [novwaul/SR3#2]
혹시 데이터셋 구성은 어떻게 해야하는지 여쭤봐도 될까요?

img_path='/home/kaist/inje/sr/data/DIV2K_train_LR_bicubic/X4',
lbl_path='/home/kaist/inje/sr/data/DIV2K_train_HR',

img_path가 64x64 이미지들이 있는 폴더 
lbl_path가 256x256 이미지들이 있는 폴더로 구성하면 될까요?

**Comment by novwaul** [comment]
답변이 늦어 죄송합니다. 말씀하신대로 구성하면 됩니다.
