### ISSUE TITLE
License of source code in GitHub repositories

### ISSUE THREAD

**Issue by tpn-emi-1-hashimoto** [novwaul/SR3#5]
Hello,

I have a few questions regarding the license of the source code in your GitHub repository.

1. Is it possible to use this source code for commercial purposes?
2. If commercial use is allowed, what are the conditions? For example, is it necessary to mention the license or place a file that contains the license information?

I would appreciate it if you could provide some clarification.

Best regards,

**Comment by novwaul** [comment]
Hello,
I sincerely appreciate your interest in my code.
As this code is an unofficial implementation, you are welcome to use it freely.
I have recently included the MIT License, so placing the license information file would be sufficient.
Thank you!

**Comment by tpn-emi-1-hashimoto** [comment]
Hello,

I sincerely appreciate your response.
This enables us to advance our development.

Thank you.
